In [1]:
import pandas as pd

In [20]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\lenovo\anaconda3\lib\site-packages (1.5.1)
Requirement already satisfied: numpy>=1.19.5 in c:\users\lenovo\anaconda3\lib\site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in c:\users\lenovo\anaconda3\lib\site-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\lenovo\anaconda3\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\lenovo\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
df=pd.read_excel(r"C:\Users\lenovo\Downloads\messy_student_marks.xlsx")

In [3]:
df

   StudyHours  PreviousResult  Attendance  FinalMarks
0           5            78.0        85.0        82.0
1           6            80.0        88.0        86.0
2           4            72.0        80.0        75.0
3           8            90.0        95.0        94.0
4           2            60.0        70.0        58.0
5           3            65.0        75.0        62.0
6           7            85.0        90.0        89.0
7           9            92.0        98.0        96.0
8           1            55.0        60.0        50.0
9           6            82.0        87.0        85.0
10          5             NaN        83.0        80.0
11        NaN            70.0        78.0        72.0
12          4            68.0         NaN        70.0
13          3            62.0        72.0         NaN
14         10            95.0       100.0        98.0
15          8            88.0        92.0        91.0
16          2            58.0        65.0        55.0
17          7            84.0        89.0        87.0
18       five            76.0        82.0        79.0
19          6            81.0        88.0        84.0
20         -1            66.0        70.0        60.0
21         12            90.0       105.0        95.0
22          4           200.0        80.0        85.0
23          3            65.0       -10.0        60.0

In [4]:
df.info

<bound method DataFrame.info of    StudyHours  PreviousResult  Attendance  FinalMarks
0           5            78.0        85.0        82.0
1           6            80.0        88.0        86.0
2           4            72.0        80.0        75.0
3           8            90.0        95.0        94.0
4           2            60.0        70.0        58.0
5           3            65.0        75.0        62.0
6           7            85.0        90.0        89.0
7           9            92.0        98.0        96.0
8           1            55.0        60.0        50.0
9           6            82.0        87.0        85.0
10          5             NaN        83.0        80.0
11        NaN            70.0        78.0        72.0
12          4            68.0         NaN        70.0
13          3            62.0        72.0         NaN
14         10            95.0       100.0        98.0
15          8            88.0        92.0        91.0
16          2            58.0        65.0        55.0
17          7            84.0        89.0        87.0
18       five            76.0        82.0        79.0
19          6            81.0        88.0        84.0
20         -1            66.0        70.0        60.0
21         12            90.0       105.0        95.0
22          4           200.0        80.0        85.0
23          3            65.0       -10.0        60.0>

In [5]:
df.dropna

<bound method DataFrame.dropna of    StudyHours  PreviousResult  Attendance  FinalMarks
0           5            78.0        85.0        82.0
1           6            80.0        88.0        86.0
2           4            72.0        80.0        75.0
3           8            90.0        95.0        94.0
4           2            60.0        70.0        58.0
5           3            65.0        75.0        62.0
6           7            85.0        90.0        89.0
7           9            92.0        98.0        96.0
8           1            55.0        60.0        50.0
9           6            82.0        87.0        85.0
10          5             NaN        83.0        80.0
11        NaN            70.0        78.0        72.0
12          4            68.0         NaN        70.0
13          3            62.0        72.0         NaN
14         10            95.0       100.0        98.0
15          8            88.0        92.0        91.0
16          2            58.0        65.0        55.0
17          7            84.0        89.0        87.0
18       five            76.0        82.0        79.0
19          6            81.0        88.0        84.0
20         -1            66.0        70.0        60.0
21         12            90.0       105.0        95.0
22          4           200.0        80.0        85.0
23          3            65.0       -10.0        60.0>

In [6]:
df.isnull()

    StudyHours  PreviousResult  Attendance  FinalMarks
0        False           False       False       False
1        False           False       False       False
2        False           False       False       False
3        False           False       False       False
4        False           False       False       False
5        False           False       False       False
6        False           False       False       False
7        False           False       False       False
8        False           False       False       False
9        False           False       False       False
10       False            True       False       False
11        True           False       False       False
12       False           False        True       False
13       False           False       False        True
14       False           False       False       False
15       False           False       False       False
16       False           False       False       False
17       False           False       False       False
18       False           False       False       False
19       False           False       False       False
20       False           False       False       False
21       False           False       False       False
22       False           False       False       False
23       False           False       False       False

In [7]:
df.isnull().sum()

StudyHours        1
PreviousResult    1
Attendance        1
FinalMarks        1
dtype: int64

In [8]:
df

   StudyHours  PreviousResult  Attendance  FinalMarks
0           5            78.0        85.0        82.0
1           6            80.0        88.0        86.0
2           4            72.0        80.0        75.0
3           8            90.0        95.0        94.0
4           2            60.0        70.0        58.0
5           3            65.0        75.0        62.0
6           7            85.0        90.0        89.0
7           9            92.0        98.0        96.0
8           1            55.0        60.0        50.0
9           6            82.0        87.0        85.0
10          5             NaN        83.0        80.0
11        NaN            70.0        78.0        72.0
12          4            68.0         NaN        70.0
13          3            62.0        72.0         NaN
14         10            95.0       100.0        98.0
15          8            88.0        92.0        91.0
16          2            58.0        65.0        55.0
17          7            84.0        89.0        87.0
18       five            76.0        82.0        79.0
19          6            81.0        88.0        84.0
20         -1            66.0        70.0        60.0
21         12            90.0       105.0        95.0
22          4           200.0        80.0        85.0
23          3            65.0       -10.0        60.0

In [12]:
df['StudyHours'] = (
    df['StudyHours']
    .replace({'five': 5})        
    .apply(pd.to_numeric, errors='coerce')
)
print(df)

    StudyHours  PreviousResult  Attendance  FinalMarks
0          5.0            78.0        85.0        82.0
1          6.0            80.0        88.0        86.0
2          4.0            72.0        80.0        75.0
3          8.0            90.0        95.0        94.0
4          2.0            60.0        70.0        58.0
5          3.0            65.0        75.0        62.0
6          7.0            85.0        90.0        89.0
7          9.0            92.0        98.0        96.0
8          1.0            55.0        60.0        50.0
9          6.0            82.0        87.0        85.0
10         5.0             NaN        83.0        80.0
11         NaN            70.0        78.0        72.0
12         4.0            68.0         NaN        70.0
13         3.0            62.0        72.0         NaN
14        10.0            95.0       100.0        98.0
15         8.0            88.0        92.0        91.0
16         2.0            58.0        65.0        55.0
17         7.0            84.0        89.0        87.0
18         5.0            76.0        82.0        79.0
19         6.0            81.0        88.0        84.0
20        -1.0            66.0        70.0        60.0
21        12.0            90.0       105.0        95.0
22         4.0           200.0        80.0        85.0
23         3.0            65.0       -10.0        60.0

C:\Users\lenovo\AppData\Local\Temp\ipykernel_6404\2100334199.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace({'five': 5})

In [15]:
num_cols = ['PreviousResult', 'Attendance', 'FinalMarks']
df[num_cols] = df[num_cols].apply(pd.to_numeric, errors='coerce')
print(df)

    StudyHours  PreviousResult  Attendance  FinalMarks
0     5.000000       78.000000   85.000000   82.000000
1     6.000000       80.000000   88.000000   86.000000
2     4.000000       72.000000   80.000000   75.000000
3     8.000000       90.000000   95.000000   94.000000
4     2.000000       60.000000   70.000000   58.000000
5     3.000000       65.000000   75.000000   62.000000
6     7.000000       85.000000   90.000000   89.000000
7     9.000000       92.000000   98.000000   96.000000
8     1.000000       55.000000   60.000000   50.000000
9     6.000000       82.000000   87.000000   85.000000
10    5.000000       80.956522   83.000000   80.000000
11    5.173913       70.000000   78.000000   72.000000
12    4.000000       68.000000   79.217391   70.000000
13    3.000000       62.000000   72.000000   77.956522
14   10.000000       95.000000  100.000000   98.000000
15    8.000000       88.000000   92.000000   91.000000
16    2.000000       58.000000   65.000000   55.000000
17    7.000000       84.000000   89.000000   87.000000
18    5.000000       76.000000   82.000000   79.000000
19    6.000000       81.000000   88.000000   84.000000
20   -1.000000       66.000000   70.000000   60.000000
21   12.000000       90.000000  105.000000   95.000000
22    4.000000      200.000000   80.000000   85.000000
23    3.000000       65.000000  -10.000000   60.000000

In [16]:
df[num_cols + ['StudyHours']] = df[num_cols + ['StudyHours']].fillna(
    df[num_cols + ['StudyHours']].mean()
)
print(df)

    StudyHours  PreviousResult  Attendance  FinalMarks
0     5.000000       78.000000   85.000000   82.000000
1     6.000000       80.000000   88.000000   86.000000
2     4.000000       72.000000   80.000000   75.000000
3     8.000000       90.000000   95.000000   94.000000
4     2.000000       60.000000   70.000000   58.000000
5     3.000000       65.000000   75.000000   62.000000
6     7.000000       85.000000   90.000000   89.000000
7     9.000000       92.000000   98.000000   96.000000
8     1.000000       55.000000   60.000000   50.000000
9     6.000000       82.000000   87.000000   85.000000
10    5.000000       80.956522   83.000000   80.000000
11    5.173913       70.000000   78.000000   72.000000
12    4.000000       68.000000   79.217391   70.000000
13    3.000000       62.000000   72.000000   77.956522
14   10.000000       95.000000  100.000000   98.000000
15    8.000000       88.000000   92.000000   91.000000
16    2.000000       58.000000   65.000000   55.000000
17    7.000000       84.000000   89.000000   87.000000
18    5.000000       76.000000   82.000000   79.000000
19    6.000000       81.000000   88.000000   84.000000
20   -1.000000       66.000000   70.000000   60.000000
21   12.000000       90.000000  105.000000   95.000000
22    4.000000      200.000000   80.000000   85.000000
23    3.000000       65.000000  -10.000000   60.000000

In [17]:
df.describe()

       StudyHours  PreviousResult  Attendance  FinalMarks
count   24.000000       24.000000   24.000000   24.000000
mean     5.173913       80.956522   79.217391   77.956522
std      2.973099       27.870006   21.986076   14.118992
min     -1.000000       55.000000  -10.000000   50.000000
25%      3.000000       65.750000   74.250000   68.000000
50%      5.000000       79.000000   82.500000   81.000000
75%      7.000000       85.750000   89.250000   87.500000
max     12.000000      200.000000  105.000000   98.000000

In [19]:
df.to_excel("cleaned_dataset.xlsx", index=False)

In [21]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [32]:
X = df[['StudyHours','PreviousResult','Attendance','FinalMarks']]
print(X)

    StudyHours  PreviousResult  Attendance  FinalMarks
0     5.000000       78.000000   85.000000   82.000000
1     6.000000       80.000000   88.000000   86.000000
2     4.000000       72.000000   80.000000   75.000000
3     8.000000       90.000000   95.000000   94.000000
4     2.000000       60.000000   70.000000   58.000000
5     3.000000       65.000000   75.000000   62.000000
6     7.000000       85.000000   90.000000   89.000000
7     9.000000       92.000000   98.000000   96.000000
8     1.000000       55.000000   60.000000   50.000000
9     6.000000       82.000000   87.000000   85.000000
10    5.000000       80.956522   83.000000   80.000000
11    5.173913       70.000000   78.000000   72.000000
12    4.000000       68.000000   79.217391   70.000000
13    3.000000       62.000000   72.000000   77.956522
14   10.000000       95.000000  100.000000   98.000000
15    8.000000       88.000000   92.000000   91.000000
16    2.000000       58.000000   65.000000   55.000000
17    7.000000       84.000000   89.000000   87.000000
18    5.000000       76.000000   82.000000   79.000000
19    6.000000       81.000000   88.000000   84.000000
20   -1.000000       66.000000   70.000000   60.000000
21   12.000000       90.000000  105.000000   95.000000
22    4.000000      200.000000   80.000000   85.000000
23    3.000000       65.000000  -10.000000   60.000000

In [28]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [33]:
preds = model.predict(X_test)
print(preds)

[61.61929582 65.53024134 78.92367912 78.35076368 77.79947042]

In [36]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [37]:
df

    StudyHours  PreviousResult  Attendance  FinalMarks
0     5.000000       78.000000   85.000000   82.000000
1     6.000000       80.000000   88.000000   86.000000
2     4.000000       72.000000   80.000000   75.000000
3     8.000000       90.000000   95.000000   94.000000
4     2.000000       60.000000   70.000000   58.000000
5     3.000000       65.000000   75.000000   62.000000
6     7.000000       85.000000   90.000000   89.000000
7     9.000000       92.000000   98.000000   96.000000
8     1.000000       55.000000   60.000000   50.000000
9     6.000000       82.000000   87.000000   85.000000
10    5.000000       80.956522   83.000000   80.000000
11    5.173913       70.000000   78.000000   72.000000
12    4.000000       68.000000   79.217391   70.000000
13    3.000000       62.000000   72.000000   77.956522
14   10.000000       95.000000  100.000000   98.000000
15    8.000000       88.000000   92.000000   91.000000
16    2.000000       58.000000   65.000000   55.000000
17    7.000000       84.000000   89.000000   87.000000
18    5.000000       76.000000   82.000000   79.000000
19    6.000000       81.000000   88.000000   84.000000
20   -1.000000       66.000000   70.000000   60.000000
21   12.000000       90.000000  105.000000   95.000000
22    4.000000      200.000000   80.000000   85.000000
23    3.000000       65.000000  -10.000000   60.000000

In [50]:
from sklearn.metrics import accuracy_score, classification_report

import numpy as np

preds_classes = (preds > 0.5).astype(int)  # Convert probabilities to binary classes

y_test = y_test.astype(int)  # Convert to integer class labels if they're floats

print("Accuracy:", accuracy_score(y_test, preds_classes))
print(classification_report(y_test, preds_classes))

Accuracy: 0.0
              precision    recall  f1-score   support

           1       0.00      0.00      0.00       0.0
          50       0.00      0.00      0.00       1.0
          55       0.00      0.00      0.00       1.0
          72       0.00      0.00      0.00       1.0
          79       0.00      0.00      0.00       1.0
          82       0.00      0.00      0.00       1.0

    accuracy                           0.00       5.0
   macro avg       0.00      0.00      0.00       5.0
weighted avg       0.00      0.00      0.00       5.0

C:\Users\lenovo\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\lenovo\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\lenovo\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\lenovo\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\lenovo\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\lenovo\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [43]:
df

    StudyHours  PreviousResult  Attendance  FinalMarks
0     5.000000       78.000000   85.000000   82.000000
1     6.000000       80.000000   88.000000   86.000000
2     4.000000       72.000000   80.000000   75.000000
3     8.000000       90.000000   95.000000   94.000000
4     2.000000       60.000000   70.000000   58.000000
5     3.000000       65.000000   75.000000   62.000000
6     7.000000       85.000000   90.000000   89.000000
7     9.000000       92.000000   98.000000   96.000000
8     1.000000       55.000000   60.000000   50.000000
9     6.000000       82.000000   87.000000   85.000000
10    5.000000       80.956522   83.000000   80.000000
11    5.173913       70.000000   78.000000   72.000000
12    4.000000       68.000000   79.217391   70.000000
13    3.000000       62.000000   72.000000   77.956522
14   10.000000       95.000000  100.000000   98.000000
15    8.000000       88.000000   92.000000   91.000000
16    2.000000       58.000000   65.000000   55.000000
17    7.000000       84.000000   89.000000   87.000000
18    5.000000       76.000000   82.000000   79.000000
19    6.000000       81.000000   88.000000   84.000000
20   -1.000000       66.000000   70.000000   60.000000
21   12.000000       90.000000  105.000000   95.000000
22    4.000000      200.000000   80.000000   85.000000
23    3.000000       65.000000  -10.000000   60.000000

In [55]:
new_student = [[12, 100, 100]]   
output= model.predict(new_student)[0]
print("PASS" if output== 1 else "FAIL")

FAIL

C:\Users\lenovo\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(